/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...any]': RouteRecordInfo<
      '/[...any]',
      '/:any(.*)',
      { any: ParamValue<true> },
      { any: ParamValue<false> },
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/analytics': RouteRecordInfo<
      '/admin/analytics',
      '/admin/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/candidate-chat/': RouteRecordInfo<
      '/admin/candidate-chat/',
      '/admin/candidate-chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/daftar-kandidat/': RouteRecordInfo<
      '/admin/daftar-kandidat/',
      '/admin/daftar-kandidat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/daftar-kandidat/[id]': RouteRecordInfo<
      '/admin/daftar-kandidat/[id]',
      '/admin/daftar-kandidat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/daftar-kandidat/penilaian-kandidat/[id]': RouteRecordInfo<
      '/admin/daftar-kandidat/penilaian-kandidat/[id]',
      '/admin/daftar-kandidat/penilaian-kandidat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/interview-schedule/': RouteRecordInfo<
      '/admin/interview-schedule/',
      '/admin/interview-schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/landing-page/': RouteRecordInfo<
      '/admin/landing-page/',
      '/admin/landing-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/landing-page/faq/': RouteRecordInfo<
      '/admin/landing-page/faq/',
      '/admin/landing-page/faq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/landing-page/informasi-perusahaan/': RouteRecordInfo<
      '/admin/landing-page/informasi-perusahaan/',
      '/admin/landing-page/informasi-perusahaan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/landing-page/kategori-bidang/': RouteRecordInfo<
      '/admin/landing-page/kategori-bidang/',
      '/admin/landing-page/kategori-bidang',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/lowongan/': RouteRecordInfo<
      '/admin/lowongan/',
      '/admin/lowongan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/lowongan/create': RouteRecordInfo<
      '/admin/lowongan/create',
      '/admin/lowongan/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/lowongan/edit/[id]': RouteRecordInfo<
      '/admin/lowongan/edit/[id]',
      '/admin/lowongan/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/lowongan/view/[id]': RouteRecordInfo<
      '/admin/lowongan/view/[id]',
      '/admin/lowongan/view/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/notifications/': RouteRecordInfo<
      '/admin/notifications/',
      '/admin/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/profile/': RouteRecordInfo<
      '/admin/profile/',
      '/admin/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/talent-needs/': RouteRecordInfo<
      '/admin/talent-needs/',
      '/admin/talent-needs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/talent-needs/[id]': RouteRecordInfo<
      '/admin/talent-needs/[id]',
      '/admin/talent-needs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/candidate/': RouteRecordInfo<
      '/candidate/',
      '/candidate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/account/': RouteRecordInfo<
      '/candidate/account/',
      '/candidate/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/chat/': RouteRecordInfo<
      '/candidate/chat/',
      '/candidate/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/notifications/': RouteRecordInfo<
      '/candidate/notifications/',
      '/candidate/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/profile/': RouteRecordInfo<
      '/candidate/profile/',
      '/candidate/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/recruitment/': RouteRecordInfo<
      '/candidate/recruitment/',
      '/candidate/recruitment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/candidate-list/': RouteRecordInfo<
      '/employee/candidate-list/',
      '/employee/candidate-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/candidate-list/[id]': RouteRecordInfo<
      '/employee/candidate-list/[id]',
      '/employee/candidate-list/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/employee/candidate-list/penilaian-kandidat/[id]': RouteRecordInfo<
      '/employee/candidate-list/penilaian-kandidat/[id]',
      '/employee/candidate-list/penilaian-kandidat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/employee/candidate-list/penilaian-kandidat/tambah/[onboardHistoryId]': RouteRecordInfo<
      '/employee/candidate-list/penilaian-kandidat/tambah/[onboardHistoryId]',
      '/employee/candidate-list/penilaian-kandidat/tambah/:onboardHistoryId',
      { onboardHistoryId: ParamValue<true> },
      { onboardHistoryId: ParamValue<false> },
      | never
    >,
    '/employee/my-team/': RouteRecordInfo<
      '/employee/my-team/',
      '/employee/my-team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/notifications/': RouteRecordInfo<
      '/employee/notifications/',
      '/employee/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/profile/': RouteRecordInfo<
      '/employee/profile/',
      '/employee/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/talent-needs/': RouteRecordInfo<
      '/employee/talent-needs/',
      '/employee/talent-needs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/talent-needs/[id]': RouteRecordInfo<
      '/employee/talent-needs/[id]',
      '/employee/talent-needs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/employee/talent-needs/ajukan-permintaan/': RouteRecordInfo<
      '/employee/talent-needs/ajukan-permintaan/',
      '/employee/talent-needs/ajukan-permintaan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/talent-needs/edit/[id]': RouteRecordInfo<
      '/employee/talent-needs/edit/[id]',
      '/employee/talent-needs/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/forgot-password/': RouteRecordInfo<
      '/forgot-password/',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/opportunities/OpportunitiesList': RouteRecordInfo<
      '/opportunities/OpportunitiesList',
      '/opportunities/OpportunitiesList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/success': RouteRecordInfo<
      '/register/success',
      '/register/success',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password/': RouteRecordInfo<
      '/reset-password/',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/': RouteRecordInfo<
      '/superadmin/',
      '/superadmin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/': RouteRecordInfo<
      '/superadmin/approval/',
      '/superadmin/approval',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/faq/': RouteRecordInfo<
      '/superadmin/approval/faq/',
      '/superadmin/approval/faq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/informasi-perusahaan/': RouteRecordInfo<
      '/superadmin/approval/informasi-perusahaan/',
      '/superadmin/approval/informasi-perusahaan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/kategori-bidang/': RouteRecordInfo<
      '/superadmin/approval/kategori-bidang/',
      '/superadmin/approval/kategori-bidang',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/audit-log/': RouteRecordInfo<
      '/superadmin/audit-log/',
      '/superadmin/audit-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/bidang/': RouteRecordInfo<
      '/superadmin/bidang/',
      '/superadmin/bidang',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/bidang/create': RouteRecordInfo<
      '/superadmin/bidang/create',
      '/superadmin/bidang/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/bidang/edit/[id]': RouteRecordInfo<
      '/superadmin/bidang/edit/[id]',
      '/superadmin/bidang/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/interview-stages/': RouteRecordInfo<
      '/superadmin/interview-stages/',
      '/superadmin/interview-stages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/interview-stages/create': RouteRecordInfo<
      '/superadmin/interview-stages/create',
      '/superadmin/interview-stages/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/interview-stages/edit/[id]': RouteRecordInfo<
      '/superadmin/interview-stages/edit/[id]',
      '/superadmin/interview-stages/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/jabatan/': RouteRecordInfo<
      '/superadmin/jabatan/',
      '/superadmin/jabatan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/jabatan/create': RouteRecordInfo<
      '/superadmin/jabatan/create',
      '/superadmin/jabatan/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/jabatan/edit/[id]': RouteRecordInfo<
      '/superadmin/jabatan/edit/[id]',
      '/superadmin/jabatan/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/notifications/': RouteRecordInfo<
      '/superadmin/notifications/',
      '/superadmin/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/posisi/': RouteRecordInfo<
      '/superadmin/posisi/',
      '/superadmin/posisi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/posisi/create': RouteRecordInfo<
      '/superadmin/posisi/create',
      '/superadmin/posisi/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/posisi/edit/[id]': RouteRecordInfo<
      '/superadmin/posisi/edit/[id]',
      '/superadmin/posisi/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/profile/': RouteRecordInfo<
      '/superadmin/profile/',
      '/superadmin/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/status-rekrutmen/': RouteRecordInfo<
      '/superadmin/status-rekrutmen/',
      '/superadmin/status-rekrutmen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/status-rekrutmen/create': RouteRecordInfo<
      '/superadmin/status-rekrutmen/create',
      '/superadmin/status-rekrutmen/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/status-rekrutmen/edit/[id]': RouteRecordInfo<
      '/superadmin/status-rekrutmen/edit/[id]',
      '/superadmin/status-rekrutmen/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/system-settings/': RouteRecordInfo<
      '/superadmin/system-settings/',
      '/superadmin/system-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/user-management/': RouteRecordInfo<
      '/superadmin/user-management/',
      '/superadmin/user-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/user-management/[id]': RouteRecordInfo<
      '/superadmin/user-management/[id]',
      '/superadmin/user-management/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/user-management/create': RouteRecordInfo<
      '/superadmin/user-management/create',
      '/superadmin/user-management/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/user-management/edit/[id]': RouteRecordInfo<
      '/superadmin/user-management/edit/[id]',
      '/superadmin/user-management/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/verify/': RouteRecordInfo<
      '/verify/',
      '/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...any].vue': {
      routes:
        | '/[...any]'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/analytics.vue': {
      routes:
        | '/admin/analytics'
      views:
        | never
    }
    'src/pages/admin/candidate-chat/index.vue': {
      routes:
        | '/admin/candidate-chat/'
      views:
        | never
    }
    'src/pages/admin/daftar-kandidat/index.vue': {
      routes:
        | '/admin/daftar-kandidat/'
      views:
        | never
    }
    'src/pages/admin/daftar-kandidat/[id].vue': {
      routes:
        | '/admin/daftar-kandidat/[id]'
      views:
        | never
    }
    'src/pages/admin/daftar-kandidat/penilaian-kandidat/[id].vue': {
      routes:
        | '/admin/daftar-kandidat/penilaian-kandidat/[id]'
      views:
        | never
    }
    'src/pages/admin/interview-schedule/index.vue': {
      routes:
        | '/admin/interview-schedule/'
      views:
        | never
    }
    'src/pages/admin/landing-page/index.vue': {
      routes:
        | '/admin/landing-page/'
      views:
        | never
    }
    'src/pages/admin/landing-page/faq/index.vue': {
      routes:
        | '/admin/landing-page/faq/'
      views:
        | never
    }
    'src/pages/admin/landing-page/informasi-perusahaan/index.vue': {
      routes:
        | '/admin/landing-page/informasi-perusahaan/'
      views:
        | never
    }
    'src/pages/admin/landing-page/kategori-bidang/index.vue': {
      routes:
        | '/admin/landing-page/kategori-bidang/'
      views:
        | never
    }
    'src/pages/admin/lowongan/index.vue': {
      routes:
        | '/admin/lowongan/'
      views:
        | never
    }
    'src/pages/admin/lowongan/create.vue': {
      routes:
        | '/admin/lowongan/create'
      views:
        | never
    }
    'src/pages/admin/lowongan/edit/[id].vue': {
      routes:
        | '/admin/lowongan/edit/[id]'
      views:
        | never
    }
    'src/pages/admin/lowongan/view/[id].vue': {
      routes:
        | '/admin/lowongan/view/[id]'
      views:
        | never
    }
    'src/pages/admin/notifications/index.vue': {
      routes:
        | '/admin/notifications/'
      views:
        | never
    }
    'src/pages/admin/profile/index.vue': {
      routes:
        | '/admin/profile/'
      views:
        | never
    }
    'src/pages/admin/talent-needs/index.vue': {
      routes:
        | '/admin/talent-needs/'
      views:
        | never
    }
    'src/pages/admin/talent-needs/[id].vue': {
      routes:
        | '/admin/talent-needs/[id]'
      views:
        | never
    }
    'src/pages/candidate/index.vue': {
      routes:
        | '/candidate/'
      views:
        | never
    }
    'src/pages/candidate/account/index.vue': {
      routes:
        | '/candidate/account/'
      views:
        | never
    }
    'src/pages/candidate/chat/index.vue': {
      routes:
        | '/candidate/chat/'
      views:
        | never
    }
    'src/pages/candidate/notifications/index.vue': {
      routes:
        | '/candidate/notifications/'
      views:
        | never
    }
    'src/pages/candidate/profile/index.vue': {
      routes:
        | '/candidate/profile/'
      views:
        | never
    }
    'src/pages/candidate/recruitment/index.vue': {
      routes:
        | '/candidate/recruitment/'
      views:
        | never
    }
    'src/pages/employee/candidate-list/index.vue': {
      routes:
        | '/employee/candidate-list/'
      views:
        | never
    }
    'src/pages/employee/candidate-list/[id].vue': {
      routes:
        | '/employee/candidate-list/[id]'
      views:
        | never
    }
    'src/pages/employee/candidate-list/penilaian-kandidat/[id].vue': {
      routes:
        | '/employee/candidate-list/penilaian-kandidat/[id]'
      views:
        | never
    }
    'src/pages/employee/candidate-list/penilaian-kandidat/tambah/[onboardHistoryId].vue': {
      routes:
        | '/employee/candidate-list/penilaian-kandidat/tambah/[onboardHistoryId]'
      views:
        | never
    }
    'src/pages/employee/my-team/index.vue': {
      routes:
        | '/employee/my-team/'
      views:
        | never
    }
    'src/pages/employee/notifications/index.vue': {
      routes:
        | '/employee/notifications/'
      views:
        | never
    }
    'src/pages/employee/profile/index.vue': {
      routes:
        | '/employee/profile/'
      views:
        | never
    }
    'src/pages/employee/talent-needs/index.vue': {
      routes:
        | '/employee/talent-needs/'
      views:
        | never
    }
    'src/pages/employee/talent-needs/[id].vue': {
      routes:
        | '/employee/talent-needs/[id]'
      views:
        | never
    }
    'src/pages/employee/talent-needs/ajukan-permintaan/index.vue': {
      routes:
        | '/employee/talent-needs/ajukan-permintaan/'
      views:
        | never
    }
    'src/pages/employee/talent-needs/edit/[id].vue': {
      routes:
        | '/employee/talent-needs/edit/[id]'
      views:
        | never
    }
    'src/pages/forgot-password/index.vue': {
      routes:
        | '/forgot-password/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/opportunities/OpportunitiesList.vue': {
      routes:
        | '/opportunities/OpportunitiesList'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
    }
    'src/pages/register/success.vue': {
      routes:
        | '/register/success'
      views:
        | never
    }
    'src/pages/reset-password/index.vue': {
      routes:
        | '/reset-password/'
      views:
        | never
    }
    'src/pages/superadmin/index.vue': {
      routes:
        | '/superadmin/'
      views:
        | never
    }
    'src/pages/superadmin/approval/index.vue': {
      routes:
        | '/superadmin/approval/'
      views:
        | never
    }
    'src/pages/superadmin/approval/faq/index.vue': {
      routes:
        | '/superadmin/approval/faq/'
      views:
        | never
    }
    'src/pages/superadmin/approval/informasi-perusahaan/index.vue': {
      routes:
        | '/superadmin/approval/informasi-perusahaan/'
      views:
        | never
    }
    'src/pages/superadmin/approval/kategori-bidang/index.vue': {
      routes:
        | '/superadmin/approval/kategori-bidang/'
      views:
        | never
    }
    'src/pages/superadmin/audit-log/index.vue': {
      routes:
        | '/superadmin/audit-log/'
      views:
        | never
    }
    'src/pages/superadmin/bidang/index.vue': {
      routes:
        | '/superadmin/bidang/'
      views:
        | never
    }
    'src/pages/superadmin/bidang/create.vue': {
      routes:
        | '/superadmin/bidang/create'
      views:
        | never
    }
    'src/pages/superadmin/bidang/edit/[id].vue': {
      routes:
        | '/superadmin/bidang/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/interview-stages/index.vue': {
      routes:
        | '/superadmin/interview-stages/'
      views:
        | never
    }
    'src/pages/superadmin/interview-stages/create.vue': {
      routes:
        | '/superadmin/interview-stages/create'
      views:
        | never
    }
    'src/pages/superadmin/interview-stages/edit/[id].vue': {
      routes:
        | '/superadmin/interview-stages/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/jabatan/index.vue': {
      routes:
        | '/superadmin/jabatan/'
      views:
        | never
    }
    'src/pages/superadmin/jabatan/create.vue': {
      routes:
        | '/superadmin/jabatan/create'
      views:
        | never
    }
    'src/pages/superadmin/jabatan/edit/[id].vue': {
      routes:
        | '/superadmin/jabatan/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/notifications/index.vue': {
      routes:
        | '/superadmin/notifications/'
      views:
        | never
    }
    'src/pages/superadmin/posisi/index.vue': {
      routes:
        | '/superadmin/posisi/'
      views:
        | never
    }
    'src/pages/superadmin/posisi/create.vue': {
      routes:
        | '/superadmin/posisi/create'
      views:
        | never
    }
    'src/pages/superadmin/posisi/edit/[id].vue': {
      routes:
        | '/superadmin/posisi/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/profile/index.vue': {
      routes:
        | '/superadmin/profile/'
      views:
        | never
    }
    'src/pages/superadmin/status-rekrutmen/index.vue': {
      routes:
        | '/superadmin/status-rekrutmen/'
      views:
        | never
    }
    'src/pages/superadmin/status-rekrutmen/create.vue': {
      routes:
        | '/superadmin/status-rekrutmen/create'
      views:
        | never
    }
    'src/pages/superadmin/status-rekrutmen/edit/[id].vue': {
      routes:
        | '/superadmin/status-rekrutmen/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/system-settings/index.vue': {
      routes:
        | '/superadmin/system-settings/'
      views:
        | never
    }
    'src/pages/superadmin/user-management/index.vue': {
      routes:
        | '/superadmin/user-management/'
      views:
        | never
    }
    'src/pages/superadmin/user-management/[id].vue': {
      routes:
        | '/superadmin/user-management/[id]'
      views:
        | never
    }
    'src/pages/superadmin/user-management/create.vue': {
      routes:
        | '/superadmin/user-management/create'
      views:
        | never
    }
    'src/pages/superadmin/user-management/edit/[id].vue': {
      routes:
        | '/superadmin/user-management/edit/[id]'
      views:
        | never
    }
    'src/pages/verify/index.vue': {
      routes:
        | '/verify/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
