/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/opportunities/OpportunitiesList': RouteRecordInfo<
      '/opportunities/OpportunitiesList',
      '/opportunities/OpportunitiesList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/success': RouteRecordInfo<
      '/register/success',
      '/register/success',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password/': RouteRecordInfo<
      '/reset-password/',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/': RouteRecordInfo<
      '/superadmin/',
      '/superadmin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/': RouteRecordInfo<
      '/superadmin/approval/',
      '/superadmin/approval',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/faq/': RouteRecordInfo<
      '/superadmin/approval/faq/',
      '/superadmin/approval/faq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/informasi-perusahaan/': RouteRecordInfo<
      '/superadmin/approval/informasi-perusahaan/',
      '/superadmin/approval/informasi-perusahaan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/approval/kategori-bidang/': RouteRecordInfo<
      '/superadmin/approval/kategori-bidang/',
      '/superadmin/approval/kategori-bidang',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/audit-log/': RouteRecordInfo<
      '/superadmin/audit-log/',
      '/superadmin/audit-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/bidang/': RouteRecordInfo<
      '/superadmin/bidang/',
      '/superadmin/bidang',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/bidang/create': RouteRecordInfo<
      '/superadmin/bidang/create',
      '/superadmin/bidang/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/bidang/edit/[id]': RouteRecordInfo<
      '/superadmin/bidang/edit/[id]',
      '/superadmin/bidang/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/interview-stages/': RouteRecordInfo<
      '/superadmin/interview-stages/',
      '/superadmin/interview-stages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/interview-stages/create': RouteRecordInfo<
      '/superadmin/interview-stages/create',
      '/superadmin/interview-stages/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/interview-stages/edit/[id]': RouteRecordInfo<
      '/superadmin/interview-stages/edit/[id]',
      '/superadmin/interview-stages/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/jabatan/': RouteRecordInfo<
      '/superadmin/jabatan/',
      '/superadmin/jabatan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/jabatan/create': RouteRecordInfo<
      '/superadmin/jabatan/create',
      '/superadmin/jabatan/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/jabatan/edit/[id]': RouteRecordInfo<
      '/superadmin/jabatan/edit/[id]',
      '/superadmin/jabatan/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/posisi/': RouteRecordInfo<
      '/superadmin/posisi/',
      '/superadmin/posisi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/posisi/create': RouteRecordInfo<
      '/superadmin/posisi/create',
      '/superadmin/posisi/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/posisi/edit/[id]': RouteRecordInfo<
      '/superadmin/posisi/edit/[id]',
      '/superadmin/posisi/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/profile/': RouteRecordInfo<
      '/superadmin/profile/',
      '/superadmin/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/status-rekrutmen/': RouteRecordInfo<
      '/superadmin/status-rekrutmen/',
      '/superadmin/status-rekrutmen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/status-rekrutmen/create': RouteRecordInfo<
      '/superadmin/status-rekrutmen/create',
      '/superadmin/status-rekrutmen/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/status-rekrutmen/edit/[id]': RouteRecordInfo<
      '/superadmin/status-rekrutmen/edit/[id]',
      '/superadmin/status-rekrutmen/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/system-settings/': RouteRecordInfo<
      '/superadmin/system-settings/',
      '/superadmin/system-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/user-management/': RouteRecordInfo<
      '/superadmin/user-management/',
      '/superadmin/user-management',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/user-management/[id]': RouteRecordInfo<
      '/superadmin/user-management/[id]',
      '/superadmin/user-management/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/superadmin/user-management/create': RouteRecordInfo<
      '/superadmin/user-management/create',
      '/superadmin/user-management/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/superadmin/user-management/edit/[id]': RouteRecordInfo<
      '/superadmin/user-management/edit/[id]',
      '/superadmin/user-management/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/verify/': RouteRecordInfo<
      '/verify/',
      '/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/opportunities/OpportunitiesList.vue': {
      routes:
        | '/opportunities/OpportunitiesList'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
    }
    'src/pages/register/success.vue': {
      routes:
        | '/register/success'
      views:
        | never
    }
    'src/pages/reset-password/index.vue': {
      routes:
        | '/reset-password/'
      views:
        | never
    }
    'src/pages/superadmin/index.vue': {
      routes:
        | '/superadmin/'
      views:
        | never
    }
    'src/pages/superadmin/approval/index.vue': {
      routes:
        | '/superadmin/approval/'
      views:
        | never
    }
    'src/pages/superadmin/approval/faq/index.vue': {
      routes:
        | '/superadmin/approval/faq/'
      views:
        | never
    }
    'src/pages/superadmin/approval/informasi-perusahaan/index.vue': {
      routes:
        | '/superadmin/approval/informasi-perusahaan/'
      views:
        | never
    }
    'src/pages/superadmin/approval/kategori-bidang/index.vue': {
      routes:
        | '/superadmin/approval/kategori-bidang/'
      views:
        | never
    }
    'src/pages/superadmin/audit-log/index.vue': {
      routes:
        | '/superadmin/audit-log/'
      views:
        | never
    }
    'src/pages/superadmin/bidang/index.vue': {
      routes:
        | '/superadmin/bidang/'
      views:
        | never
    }
    'src/pages/superadmin/bidang/create.vue': {
      routes:
        | '/superadmin/bidang/create'
      views:
        | never
    }
    'src/pages/superadmin/bidang/edit/[id].vue': {
      routes:
        | '/superadmin/bidang/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/interview-stages/index.vue': {
      routes:
        | '/superadmin/interview-stages/'
      views:
        | never
    }
    'src/pages/superadmin/interview-stages/create.vue': {
      routes:
        | '/superadmin/interview-stages/create'
      views:
        | never
    }
    'src/pages/superadmin/interview-stages/edit/[id].vue': {
      routes:
        | '/superadmin/interview-stages/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/jabatan/index.vue': {
      routes:
        | '/superadmin/jabatan/'
      views:
        | never
    }
    'src/pages/superadmin/jabatan/create.vue': {
      routes:
        | '/superadmin/jabatan/create'
      views:
        | never
    }
    'src/pages/superadmin/jabatan/edit/[id].vue': {
      routes:
        | '/superadmin/jabatan/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/posisi/index.vue': {
      routes:
        | '/superadmin/posisi/'
      views:
        | never
    }
    'src/pages/superadmin/posisi/create.vue': {
      routes:
        | '/superadmin/posisi/create'
      views:
        | never
    }
    'src/pages/superadmin/posisi/edit/[id].vue': {
      routes:
        | '/superadmin/posisi/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/profile/index.vue': {
      routes:
        | '/superadmin/profile/'
      views:
        | never
    }
    'src/pages/superadmin/status-rekrutmen/index.vue': {
      routes:
        | '/superadmin/status-rekrutmen/'
      views:
        | never
    }
    'src/pages/superadmin/status-rekrutmen/create.vue': {
      routes:
        | '/superadmin/status-rekrutmen/create'
      views:
        | never
    }
    'src/pages/superadmin/status-rekrutmen/edit/[id].vue': {
      routes:
        | '/superadmin/status-rekrutmen/edit/[id]'
      views:
        | never
    }
    'src/pages/superadmin/system-settings/index.vue': {
      routes:
        | '/superadmin/system-settings/'
      views:
        | never
    }
    'src/pages/superadmin/user-management/index.vue': {
      routes:
        | '/superadmin/user-management/'
      views:
        | never
    }
    'src/pages/superadmin/user-management/[id].vue': {
      routes:
        | '/superadmin/user-management/[id]'
      views:
        | never
    }
    'src/pages/superadmin/user-management/create.vue': {
      routes:
        | '/superadmin/user-management/create'
      views:
        | never
    }
    'src/pages/superadmin/user-management/edit/[id].vue': {
      routes:
        | '/superadmin/user-management/edit/[id]'
      views:
        | never
    }
    'src/pages/verify/index.vue': {
      routes:
        | '/verify/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
