/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...any]': RouteRecordInfo<
      '/[...any]',
      '/:any(.*)',
      { any: ParamValue<true> },
      { any: ParamValue<false> },
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/candidate-chat/': RouteRecordInfo<
      '/admin/candidate-chat/',
      '/admin/candidate-chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/cms/': RouteRecordInfo<
      '/admin/cms/',
      '/admin/cms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/daftar-kandidat/': RouteRecordInfo<
      '/admin/daftar-kandidat/',
      '/admin/daftar-kandidat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/daftar-kandidat/[id]': RouteRecordInfo<
      '/admin/daftar-kandidat/[id]',
      '/admin/daftar-kandidat/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/dashboard/': RouteRecordInfo<
      '/admin/dashboard/',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/interview-schedule/': RouteRecordInfo<
      '/admin/interview-schedule/',
      '/admin/interview-schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/talent-needs/': RouteRecordInfo<
      '/admin/talent-needs/',
      '/admin/talent-needs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/candidate-list/': RouteRecordInfo<
      '/employee/candidate-list/',
      '/employee/candidate-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/my-team/': RouteRecordInfo<
      '/employee/my-team/',
      '/employee/my-team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/talent-needs/': RouteRecordInfo<
      '/employee/talent-needs/',
      '/employee/talent-needs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employee/talent-needs/ajukan-permintaan/': RouteRecordInfo<
      '/employee/talent-needs/ajukan-permintaan/',
      '/employee/talent-needs/ajukan-permintaan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...any].vue': {
      routes:
        | '/[...any]'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/candidate-chat/index.vue': {
      routes:
        | '/admin/candidate-chat/'
      views:
        | never
    }
    'src/pages/admin/cms/index.vue': {
      routes:
        | '/admin/cms/'
      views:
        | never
    }
    'src/pages/admin/daftar-kandidat/index.vue': {
      routes:
        | '/admin/daftar-kandidat/'
      views:
        | never
    }
    'src/pages/admin/daftar-kandidat/[id].vue': {
      routes:
        | '/admin/daftar-kandidat/[id]'
      views:
        | never
    }
    'src/pages/admin/dashboard/index.vue': {
      routes:
        | '/admin/dashboard/'
      views:
        | never
    }
    'src/pages/admin/interview-schedule/index.vue': {
      routes:
        | '/admin/interview-schedule/'
      views:
        | never
    }
    'src/pages/admin/talent-needs/index.vue': {
      routes:
        | '/admin/talent-needs/'
      views:
        | never
    }
    'src/pages/employee/candidate-list/index.vue': {
      routes:
        | '/employee/candidate-list/'
      views:
        | never
    }
    'src/pages/employee/my-team/index.vue': {
      routes:
        | '/employee/my-team/'
      views:
        | never
    }
    'src/pages/employee/talent-needs/index.vue': {
      routes:
        | '/employee/talent-needs/'
      views:
        | never
    }
    'src/pages/employee/talent-needs/ajukan-permintaan/index.vue': {
      routes:
        | '/employee/talent-needs/ajukan-permintaan/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}